"""
seed.py — Popula o banco com mensagens completas para TODOS os widgets.
Cada widget da tela inicial tem sua própria categoria com 30+ mensagens únicas.
Execute: python seed.py
         python seed.py --reset   (apaga e recria tudo)
"""
from app import create_app, db
from app.models.message import Category, Message
from app.models.reminder import Reminder

# ── Categorias ────────────────────────────────────────────────────────────────
CATEGORIES = [
    # Categorias principais (app interno)
    {"slug": "daily",          "name": "Mensagem do Dia",        "emoji": "🌸"},
    {"slug": "health",         "name": "Dicas de Saúde",         "emoji": "💚"},
    {"slug": "nutrition",      "name": "Nutrição",                "emoji": "🥗"},
    {"slug": "curiosity",      "name": "Curiosidades",            "emoji": "✨"},
    {"slug": "medical",        "name": "Alertas Médicos",         "emoji": "🏥"},
    # Categorias dos widgets da tela inicial
    {"slug": "strength",       "name": "Força",                   "emoji": "💪"},
    {"slug": "nature",         "name": "Natureza",                "emoji": "🌿"},
    {"slug": "serenity",       "name": "Serenidade",              "emoji": "☮️"},
    {"slug": "ocean",          "name": "Oceano",                  "emoji": "🌊"},
    {"slug": "body",           "name": "Seu Corpo",               "emoji": "🫶"},
    {"slug": "tenderness",     "name": "Ternura",                 "emoji": "💕"},
    {"slug": "night",          "name": "Mensagem da Noite",       "emoji": "🌙"},
    {"slug": "floral",         "name": "Floral",                  "emoji": "🌺"},
    {"slug": "sunrise",        "name": "Mensagem do Sol",         "emoji": "☀️"},
    {"slug": "transformation", "name": "Transformação",           "emoji": "🦋"},
]

# ── 200 MENSAGENS DO DIA (daily) ──────────────────────────────────────────────
DAILY = [
    ("Você está fazendo um trabalho incrível. Cada dia é uma pequena vitória na sua jornada.", 1, 42),
    ("Você é mais forte do que imagina. Confie no seu corpo e no seu instinto materno.", 1, 42),
    ("Cada momento da sua gravidez é único e precioso. Saboreie esta fase.", 1, 42),
    ("Você não precisa ser perfeita. Você só precisa ser você — e isso já é mais que suficiente.", 1, 42),
    ("Você já virou mamãe no coração. Que conquista extraordinária.", 1, 42),
    ("Abraçe alguém que você ama hoje. O amor é energia positiva para vocês dois.", 1, 42),
    ("Você está criando vida — algo verdadeiramente mágico acontece dentro de você.", 1, 42),
    ("Você merece um momento só seu. Cuide de si com carinho e atenção.", 1, 42),
    ("Cada batida do coração do seu bebê é uma sinfonia de vida e amor.", 1, 42),
    ("Sua jornada é única. Não compare sua gestação com a de ninguém.", 1, 42),
    ("O amor que você já sente por esse bebê é a coisa mais poderosa do mundo.", 1, 42),
    ("Neste momento, você é a pessoa mais importante do mundo para alguém.", 1, 42),
    ("Permita-se sentir tudo — a alegria, o cansaço, a emoção. Tudo é válido.", 1, 42),
    ("Seu corpo sabe o que está fazendo. Confie nele.", 1, 42),
    ("Cada cólica, cada náusea, cada desconforto tem um propósito maior.", 1, 42),
    ("Você está escrevendo a história mais bonita da sua vida.", 1, 42),
    ("Hoje, concentre-se em uma coisa que te faz feliz e repita-a.", 1, 42),
    ("Sua calma é a calma do seu bebê. Respire fundo.", 1, 42),
    ("Você é a primeira casa do seu filho. Que honra imensa.", 1, 42),
    ("Cada semana superada é uma conquista para celebrar.", 1, 42),
    ("Não existe gestação certa ou errada. Existe a sua, e ela é perfeita.", 1, 42),
    ("Hoje você é um milagre carregando outro milagre.", 1, 42),
    ("A força que você demonstra todos os dias é inspiradora.", 1, 42),
    ("Seu bebê já sente seu amor. Ele cresce envolto nele.", 1, 42),
    ("Permita-se descansar sem culpa. Seu corpo está trabalhando intensamente.", 1, 42),
    ("Cada manhã que você acorda, você dá mais um dia de vida ao seu bebê.", 1, 42),
    ("Você está no caminho certo, mesmo quando parece difícil.", 1, 42),
    ("A maternidade começa agora, neste exato momento.", 1, 42),
    ("Você é capaz de tudo que este momento exige de você.", 1, 42),
    ("Pequenos momentos de alegria durante a gestação alimentam sua alma.", 1, 42),
    ("Neste primeiro trimestre, seu corpo está fazendo algo extraordinário. Descanse.", 1, 13),
    ("A náusea pode ser difícil, mas é sinal de que tudo está progredindo.", 1, 12),
    ("No segundo trimestre, muitas mamães se sentem mais dispostas. Aproveite!", 14, 26),
    ("Você está na metade da jornada — olhe o quanto já percorreu!", 20, 20),
    ("No terceiro trimestre, cada semana conta. Você está quase lá!", 27, 42),
    ("Em breve você vai segurar nas mãos aquele que já segurou seu coração.", 35, 42),
    ("Cada contração é um passo mais perto do seu filho.", 37, 42),
    ("Falta pouco para o grande encontro. Que emoção!", 27, 42),
    ("Você foi feita para isso. Confie no processo.", 37, 42),
    ("Em breve, as noites sem dormir vão ser as mais preciosas da sua vida.", 38, 42),
    ("Hoje vai ser um bom dia. Decida isso logo pela manhã.", 1, 42),
    ("Você pode não ter todas as respostas — e isso não te faz menos mãe.", 1, 42),
    ("Encontre beleza nos pequenos detalhes de hoje.", 1, 42),
    ("Sua intuição materna já está ativa. Confie nela.", 1, 42),
    ("Um copo de água agora. Você e o bebê merecem.", 1, 42),
    ("Sua história de amor com seu filho começou muito antes do nascimento.", 1, 42),
    ("Respire. Você está exatamente onde precisa estar.", 1, 42),
    ("Não existe jeito errado de amar seu filho.", 1, 42),
    ("Você transformou sua vida para dar vida. Isso é extraordinário.", 1, 42),
    ("Seu bebê já sente a diferença quando você está tranquila. Procure a paz.", 1, 42),
    ("A gestação é uma conversa silenciosa entre dois corações.", 1, 42),
    ("O que te assusta hoje vai se tornar sua maior conquista amanhã.", 1, 42),
    ("Pedir ajuda é um ato de coragem, não de fraqueza.", 1, 42),
    ("Seu bebê precisa de uma mãe feliz mais do que de uma mãe perfeita.", 1, 42),
    ("Olhe para o quanto você já cresceu desde o começo desta jornada.", 1, 42),
    ("Hoje, agradeça por uma coisa pequena e bonita da sua gestação.", 1, 42),
    ("Você está construindo os alicerces da vida de alguém. Que responsabilidade linda.", 1, 42),
    ("Fale com seu bebê. Ele reconhece seu timbre de voz.", 1, 42),
    ("Um sorriso seu hoje é um regalo para o seu bebê.", 1, 42),
    ("A canseira que você sente é a evidência de quanto você se dedica.", 1, 42),
    ("Cada roupinha, cada fralda preparada é amor em forma de objeto.", 1, 42),
    ("Hoje, trate-se com a delicadeza que você trataria outra grávida.", 1, 42),
    ("Sua gestação é sagrada. Proteja sua paz.", 1, 42),
    ("Tudo que você experimenta agora fica gravado na história do seu filho.", 1, 42),
    ("Você é a continuação e o começo de algo muito maior do que você.", 1, 42),
    ("Que a calma chegue até você como uma onda suave hoje.", 1, 42),
    ("O amanhã vai ser melhor. E você vai estar lá para vê-lo.", 1, 42),
    ("Converse com seu bebê como se ele já entendesse tudo — porque ele sente.", 1, 42),
    ("Você é a protagonista desta história. Cuide bem de si.", 1, 42),
    ("Hoje, permita-se apenas existir e sentir.", 1, 42),
    ("Esta fase vai passar — e você vai sentir saudade dela.", 1, 42),
    ("O que acontece dentro de você agora vai mudar o mundo.", 1, 42),
    ("Você carrega consigo toda a força das mães que vieram antes de você.", 1, 42),
    ("Hoje é um dia para confiar mais em si mesma.", 1, 42),
    ("Você é incrivelmente capaz — mesmo nos momentos em que duvida disso.", 1, 42),
    ("O filho que você espera já é a história mais bonita que você tem para contar.", 1, 42),
    ("Você é exatamente a mãe que este bebê precisa.", 1, 42),
    ("O cansaço de hoje vai virar lembrança bonita amanhã.", 1, 42),
    ("Prepare seu coração — o amor mais avassalador está a caminho.", 1, 42),
    ("Cada detalhe desta gestação é digno de atenção e carinho.", 1, 42),
    ("Você tem o suporte do universo nessa caminhada.", 1, 42),
    ("Hoje, olhe para o seu ventre e sinta seu bebê perto.", 1, 42),
    ("Ser mãe é a maior aventura. Você já começou.", 1, 42),
    ("Você transforma amor em vida, todos os dias.", 1, 42),
    ("A vida que você está gerando vai tocar muitas outras vidas.", 1, 42),
    ("Seja paciente com você mesma — você está aprendendo algo novo a cada dia.", 1, 42),
    ("O universo escolheu você para ser a mãe deste bebê. Não foi por acaso.", 1, 42),
    ("Hoje, um passo de cada vez. Isso é suficiente.", 1, 42),
    ("Você é mais do que o suficiente para esta missão.", 1, 42),
    ("Sua gravidez é a promessa mais bonita que você já fez.", 1, 42),
    ("Você vai se surpreender com quanto amor é capaz de sentir.", 1, 42),
    ("Cada momento desta gestação é irrepetível e precioso.", 1, 42),
    ("Hoje você está um dia mais perto do momento mais lindo da sua vida.", 1, 42),
    ("Que os desconfortos de hoje sejam lembranças suaves amanhã.", 1, 42),
    ("O amor de mãe é a força gravitacional do universo emocional.", 1, 42),
    ("Cada história que você conta para o bebê fica guardada nele.", 1, 42),
    ("Sua gestação é um capítulo que você vai querer reler muitas vezes.", 1, 42),
    ("Nada é mais bonito do que uma mãe amando seu filho antes de vê-lo.", 1, 42),
    ("Hoje, faça uma coisa só por você. Você merece.", 1, 42),
]

# ── FORÇA (strength) — 35 mensagens ──────────────────────────────────────────
STRENGTH = [
    ("Você tem uma força que nem imagina. Ela cresce a cada dia dessa gestação.", 1, 42),
    ("Cada dificuldade que você supera te torna mais preparada para o que vem.", 1, 42),
    ("A força de uma mãe não conhece limites. E você já é mãe.", 1, 42),
    ("Você enfrentou cada desconforto com coragem. Isso é força real.", 1, 42),
    ("Dentro de você existe uma guerreira que protege seu filho com o próprio corpo.", 1, 42),
    ("Carregar uma vida é o ato mais poderoso que existe. E você faz isso todos os dias.", 1, 42),
    ("Sua determinação de cuidar bem do seu bebê é a maior prova de força.", 1, 42),
    ("Nos dias difíceis, lembre: você é mais forte do que aquilo que sente agora.", 1, 42),
    ("A força que você não sabia que tinha se revela nessa jornada.", 1, 42),
    ("Você passou por noites difíceis e manhãs pesadas — e está aqui. Isso é força.", 1, 13),
    ("Cada exame, cada consulta enfrentada é um ato de coragem.", 1, 42),
    ("Mesmo nos momentos de medo, você continua. Isso define a força de uma mãe.", 1, 42),
    ("Você não precisa ser invencível — só precisa continuar. E você continua.", 1, 42),
    ("A força não é ausência de medo. É seguir mesmo com ele.", 1, 42),
    ("Seu corpo está realizando o mais complexo trabalho da natureza. Que força.", 1, 42),
    ("Você está construindo não apenas um filho, mas uma versão mais forte de si.", 1, 42),
    ("Cada manhã que você escolhe cuidar de si e do bebê é um ato de bravura.", 1, 42),
    ("A coragem não grita. Às vezes ela sussurra: eu consigo mais um dia.", 1, 42),
    ("Você já superou mais do que imagina. Esse bebê tem uma mãe muito forte.", 1, 42),
    ("A força real está em pedir ajuda quando precisa. Você sabe disso.", 1, 42),
    ("Você vai passar pelo parto e vai descobrir uma força que ainda não conhece.", 27, 42),
    ("No terceiro trimestre o corpo pesa, mas o espírito se fortalece.", 27, 42),
    ("Falta pouco. Toda a sua força foi construída para este momento final.", 35, 42),
    ("Cada respiração profunda é um exercício de força e presença.", 1, 42),
    ("Você é prova de que o amor pode ser mais forte que qualquer medo.", 1, 42),
    ("Sua vulnerabilidade não é fraqueza — é a coragem de sentir tudo.", 1, 42),
    ("A gestação te desafiou e você respondeu com amor. Isso é extraordinário.", 1, 42),
    ("Você protege, nutre e ama. A força da maternidade é incomparável.", 1, 42),
    ("Cada dia nessa jornada te torna mais sábia e mais forte.", 1, 42),
    ("Sua força não é só sua — ela passa para o bebê através de cada célula.", 1, 42),
    ("O coração de uma mãe é o lugar mais forte e mais gentil que existe.", 1, 42),
    ("Você vai enfrentar o parto com a mesma garra que enfrentou tudo até aqui.", 35, 42),
    ("Toda dificuldade superada durante a gestação foi treinamento para a maternidade.", 1, 42),
    ("Você já mostrou ao seu bebê o que é ter uma mãe resiliente.", 1, 42),
    ("Essa criança vai crescer sabendo o que é força — porque vai te observar.", 1, 42),
]

# ── NATUREZA (nature) — 35 mensagens ─────────────────────────────────────────
NATURE = [
    ("Como a semente que se transforma em árvore, seu bebê cresce com a força da natureza.", 1, 42),
    ("A natureza criou o milagre da vida dentro de você. Conecte-se com ela hoje.", 1, 42),
    ("Uma caminhada ao ar livre faz bem à alma da mãe e ao desenvolvimento do bebê.", 1, 42),
    ("O ritmo das estações reflete o ritmo da gravidez: cada fase tem sua beleza.", 1, 42),
    ("Como as raízes nutrem a árvore, você nutre seu filho com amor e cuidado.", 1, 42),
    ("A natureza não tem pressa — e sua gestação também tem seu tempo perfeito.", 1, 42),
    ("Inspire o ar fresco. A natureza regenera o que o cansaço consome.", 1, 42),
    ("Seu corpo é natureza pura: sabe como criar, nutrir e proteger uma vida.", 1, 42),
    ("As plantas crescem em direção à luz. Seu bebê cresce em direção ao seu amor.", 1, 42),
    ("Um momento em um jardim, um parque ou perto de uma árvore pode renovar sua energia.", 1, 42),
    ("A terra nutre as sementes sem julgá-las. Você também pode se nutrir sem julgamentos.", 1, 42),
    ("Como os rios encontram o mar, você e seu bebê estão seguindo o caminho certo.", 1, 42),
    ("A natureza criou seu corpo para exatamente isso que você está vivendo agora.", 1, 42),
    ("Observe como as plantas florescem sem esforço — confie no seu florescimento.", 1, 42),
    ("O silêncio da natureza às vezes é tudo o que precisamos para encontrar paz.", 1, 42),
    ("Cada fruta, cada folha verde no seu prato é a natureza cuidando de você.", 1, 42),
    ("Como o sol nasce todos os dias, cada manhã traz uma nova chance de conexão com seu bebê.", 1, 42),
    ("O cheiro de terra depois da chuva. A brisa na pele. São esses detalhes que restauram.", 1, 42),
    ("Sua gravidez é um fenômeno natural tão grandioso quanto qualquer maravilha do mundo.", 1, 42),
    ("A natureza está do seu lado: cada processo do seu corpo é sabedoria ancestral.", 1, 42),
    ("Coloque os pés na terra, respire fundo. O presente é aqui.", 1, 42),
    ("Como as flores precisam de água, você precisa de cuidado. Cuide-se hoje.", 1, 42),
    ("A natureza ensina: depois da tempestade vem a calma. Depois do parto, vem o encontro.", 35, 42),
    ("Você faz parte de um ciclo natural de amor e vida que sempre existiu.", 1, 42),
    ("A conexão com a natureza durante a gestação traz paz para mãe e bebê.", 1, 42),
    ("Como a lua cheia ilumina a noite, seu amor ilumina o mundo do seu bebê.", 1, 42),
    ("Coma alimentos da terra hoje: nutritivos, coloridos e cheios de vida.", 1, 42),
    ("A natureza criou o parto como uma dança — seu corpo sabe os passos.", 35, 42),
    ("Como as árvores guardam história nos anéis, você guarda amor em cada célula.", 1, 42),
    ("O ritmo da natureza é o ritmo do seu coração: constante, forte e presente.", 1, 42),
    ("Toda semente carrega a promessa de uma floresta. Você carrega a promessa de uma vida.", 1, 42),
    ("A natureza criou mães e bebês para se encontrarem. Esse encontro está chegando.", 35, 42),
    ("Cada flor que desabrocha lembra que a transformação é natural e bela.", 1, 42),
    ("Você é natureza gerando natureza. Que processo sagrado.", 1, 42),
    ("A calma que a natureza oferece é a mesma que você pode oferecer ao seu bebê.", 1, 42),
]

# ── SERENIDADE (serenity) — 35 mensagens ─────────────────────────────────────
SERENITY = [
    ("Pare por um momento. Respire. Você está bem.", 1, 42),
    ("A serenidade não é ausência de problemas — é paz apesar deles.", 1, 42),
    ("Em cada respiração profunda existe um presente para você e para o seu bebê.", 1, 42),
    ("Que sua mente encontre descanso hoje. O corpo já está trabalhando muito.", 1, 42),
    ("A paz interior que você cultiva passa diretamente para o seu filho.", 1, 42),
    ("Você não precisa resolver tudo agora. Basta estar presente.", 1, 42),
    ("Feche os olhos por um momento. Sinta a vida que existe dentro de você.", 1, 42),
    ("A serenidade é um presente que você dá a si mesma e ao seu bebê.", 1, 42),
    ("Deixe ir o que não está sob seu controle. Segure o que importa.", 1, 42),
    ("Um banho quente, uma música calma, uma xícara de chá. A paz está nos detalhes.", 1, 42),
    ("Quando a ansiedade chegar, respire: inspire contando até 4, expire contando até 6.", 1, 42),
    ("Seu bebê sente sua serenidade como um abraço quente e contínuo.", 1, 42),
    ("Hoje, escolha deliberadamente um momento de silêncio para si mesma.", 1, 42),
    ("A gestação ensina que nem tudo precisa ser apressado. Que presente.", 1, 42),
    ("Como o lago calmo reflete o céu, sua serenidade reflete amor ao seu bebê.", 1, 42),
    ("Você pode estar cansada e ainda assim estar em paz. As duas coisas coexistem.", 1, 42),
    ("A meditação de 5 minutos pode transformar o seu dia inteiro.", 1, 42),
    ("Serenidade não é passividade — é agir com calma e presença.", 1, 42),
    ("Liberte-se da preocupação com o futuro por alguns instantes. O agora é suficiente.", 1, 42),
    ("Que as preocupações de amanhã esperem por amanhã. Hoje, seja só presença.", 1, 42),
    ("Seu bebê aprende com sua calma que o mundo pode ser um lugar seguro.", 1, 42),
    ("A paz que você busca está mais perto do que imagina — está dentro de você.", 1, 42),
    ("Músicas suaves, luz baixa, almofadas confortáveis. Crie seu santuário de paz.", 27, 42),
    ("No terceiro trimestre, a serenidade é especialmente valiosa. Busque-a ativamente.", 27, 42),
    ("Você não precisa de respostas para tudo. Algumas coisas se resolvem com o tempo.", 1, 42),
    ("Cada momento sereno durante a gestação é um investimento no bem-estar do bebê.", 1, 42),
    ("A gentileza com você mesma é o caminho mais curto para a serenidade.", 1, 42),
    ("Desligue o celular por uma hora. Existe vida e paz além das telas.", 1, 42),
    ("Que sua mente descanse enquanto seu coração faz o trabalho de amar.", 1, 42),
    ("A respiração é sempre um porto seguro nos momentos de turbulência.", 1, 42),
    ("Encontre um lugar bonito e sente-se em silêncio por alguns minutos hoje.", 1, 42),
    ("A serenidade que você pratica agora prepara o bebê para um mundo mais calmo.", 1, 42),
    ("Você merece paz — não depois do parto, não depois de resolver tudo. Agora.", 1, 42),
    ("Como o oceano tem ondas mas permanece profundo, você pode ter emoções e ainda ter paz.", 1, 42),
    ("Hoje, seja apenas mãe grávida. Sem cobranças extras. Só isso.", 1, 42),
]

# ── OCEANO (ocean) — 35 mensagens ────────────────────────────────────────────
OCEAN = [
    ("Como o oceano abraça todas as costas, seu amor abraça seu filho de todos os lados.", 1, 42),
    ("As ondas do oceano vêm e vão — assim como as fases difíceis desta gestação.", 1, 42),
    ("Sua gestação é profunda como o mar: cheia de mistérios e maravilhas.", 1, 42),
    ("O líquido amniótico onde seu bebê nada é o seu oceano particular.", 1, 42),
    ("Como o mar nunca para de se mover, seu amor por esse bebê nunca para de crescer.", 1, 42),
    ("A profundidade do oceano lembra a profundidade do amor que você já sente.", 1, 42),
    ("Água, sal e movimento — ingredientes do oceano e da vida que você carrega.", 1, 42),
    ("O oceano é imenso, mas cada gota importa. Cada momento com seu bebê importa.", 1, 42),
    ("Como os peixes nadam em harmonia com a água, seu bebê nada em harmonia com você.", 1, 42),
    ("Hidrate-se bem hoje. Água é vida — para você e para o oceano do seu bebê.", 1, 42),
    ("O oceano tem tempestades, mas sempre volta à calma. Você também.", 1, 42),
    ("Imagine as ondas levando suas preocupações embora. Inspire. Expire.", 1, 42),
    ("O mar tem marés — assim sua gravidez tem altos e baixos. Tudo é natural.", 1, 42),
    ("Como o oceano abraça a areia, você vai abraçar seu bebê em breve.", 35, 42),
    ("A vastidão do oceano lembra que seu amor não tem fronteiras.", 1, 42),
    ("Água é essencial. Beba pelo menos 2 litros hoje para nutrir o pequeno oceano do bebê.", 1, 42),
    ("Como as ondas moldam a costa, a gestação está moldando você de formas belas.", 1, 42),
    ("O oceano é salgado como as lágrimas de alegria que você vai derramar no parto.", 35, 42),
    ("Nadar ou apenas ouvir o som do mar tem poder calmante comprovado para gestantes.", 1, 42),
    ("A força do oceano está em sua constância — assim como o seu cuidado diário.", 1, 42),
    ("Como corais formam estruturas complexas com paciência, você constrói um ser humano.", 1, 42),
    ("O oceano nutre a vida em suas profundezas — você também faz isso.", 1, 42),
    ("A maré alta virá. O seu encontro com o bebê está se aproximando.", 35, 42),
    ("Banho de mar ou ducha longa: a água restaura a energia das gestantes.", 1, 42),
    ("Como os golfinhos pulam livremente, seu bebê se mexe feliz dentro de você.", 14, 42),
    ("O horizonte do oceano lembra que sempre existe algo além do que podemos ver agora.", 1, 42),
    ("A água é símbolo de vida, renovação e pureza. Você carrega tudo isso.", 1, 42),
    ("Como o oceano aceita todos os rios, você vai aceitar e amar todas as partes do seu filho.", 1, 42),
    ("A paciência do oceano é infinita. A sua, como mãe, também vai ser.", 1, 42),
    ("Como as correntes marítimas têm direção certa, sua gestação também tem.", 1, 42),
    ("O sal do mar purifica. Que suas lágrimas de emoção também sejam purificadoras.", 1, 42),
    ("Como as estrelas do mar se regeneram, você se regenera a cada noite de sono.", 1, 42),
    ("O oceano tem profundidade que o olho não alcança. Assim é o amor de mãe.", 1, 42),
    ("Que o ritmo das ondas guie sua respiração hoje: calma, constante e viva.", 1, 42),
    ("Como o oceano guarda segredos em suas profundezas, você guarda a vida.", 1, 42),
]

# ── SEU CORPO (body) — 35 mensagens ──────────────────────────────────────────
BODY = [
    ("Seu corpo está realizando o processo mais complexo da natureza. Respeite-o.", 1, 42),
    ("Cada mudança no seu corpo é evidência de vida e amor. Não lute contra elas.", 1, 42),
    ("Seu corpo é seu melhor aliado nessa gestação. Ouça o que ele tem a dizer.", 1, 42),
    ("As estrias são marcas de crescimento — do bebê e do seu amor.", 1, 42),
    ("Seu coração aumentou de tamanho para bombear mais sangue ao bebê. Que fato lindo.", 8, 42),
    ("Seu útero cresceu de um limão para uma melancia. Que incrível transformação.", 1, 42),
    ("Seu nariz afiou o olfato para proteger o bebê de substâncias nocivas.", 1, 42),
    ("Seus seios estão se preparando para o milagre da amamentação.", 1, 42),
    ("Sua pele está mais sensível porque está abrigando uma nova vida.", 1, 42),
    ("A barriga que cresce é o sinal mais visível de que você está cumprindo sua missão.", 14, 42),
    ("O ligamento redondo dói porque seu útero se expande para dar mais espaço ao bebê.", 14, 26),
    ("O cansaço que você sente é real — produzir vida consome energia real.", 1, 13),
    ("Seu volume sanguíneo aumentou 50% para nutrir dois corações.", 8, 42),
    ("A musculatura do seu assoalho pélvico trabalha incansavelmente. Fortaleça-a.", 10, 42),
    ("Seu corpo produz a placenta — um órgão temporário que sustenta uma vida inteira.", 1, 42),
    ("Sua voz reconforta o bebê desde a 18ª semana. Cante, fale, sussurre.", 18, 42),
    ("O inchaço nos pés é seu corpo redistributing fluidos para proteger o bebê.", 25, 42),
    ("Seu intestino trabalha mais devagar para absorver mais nutrientes ao bebê.", 1, 42),
    ("A cólica nas costas aparece porque seu centro de gravidade mudou. É normal.", 14, 42),
    ("Seu cérebro literalmente muda de estrutura durante a gestação. A neurociência confirma.", 1, 42),
    ("O reflexo de ânsia foi criado para te proteger de alimentos nocivos ao bebê.", 1, 12),
    ("Cada quilinho a mais no seu corpo é amor em forma de nutrição para o bebê.", 1, 42),
    ("Seu sistema imune ajusta-se para não rejeitar o bebê. Que sabedoria corporal.", 1, 42),
    ("A pressão na bexiga é o bebê crescendo — sinal de que tudo vai bem.", 14, 42),
    ("Seus quadris estão se preparando para o parto com relaxina. Confie no processo.", 27, 42),
    ("A posição que você acha mais confortável para dormir é exatamente a certa.", 20, 42),
    ("Seu corpo produz leite antes mesmo do bebê nascer. Que preparação incrível.", 35, 42),
    ("As contraturas de Braxton Hicks são treinos do útero para o grande dia.", 28, 42),
    ("Seu rosto pode mudar, sua pele pode ser diferente — e você está mais bonita.", 1, 42),
    ("O calor que você sente é seu metabolismo acelerado trabalhando para dois.", 1, 42),
    ("Seu corpo está escrevendo o manual da maternidade com cada célula.", 1, 42),
    ("Escute os sinais que seu corpo dá: cansaço pede descanso, fome pede alimento.", 1, 42),
    ("Você e seu corpo estão em parceria perfeita para trazer essa vida ao mundo.", 1, 42),
    ("Seu corpo sabe o momento certo para iniciar o trabalho de parto.", 37, 42),
    ("Agradece ao seu corpo hoje. Ele está dando tudo por você e pelo bebê.", 1, 42),
]

# ── TERNURA (tenderness) — 35 mensagens ──────────────────────────────────────
TENDERNESS = [
    ("O amor mais suave do mundo está crescendo dentro de você.", 1, 42),
    ("Há uma ternura única em tocar sua própria barriga e saber que alguém está lá.", 1, 42),
    ("Seu bebê já é amado de um jeito que nenhuma palavra consegue descrever.", 1, 42),
    ("A suavidade com que você cuida do seu bebê já antes do nascimento é rara.", 1, 42),
    ("Existe algo sagrado no silêncio de uma mãe que contempla seu filho por vir.", 1, 42),
    ("O vínculo que vocês têm já é real, profundo e cheio de ternura.", 1, 42),
    ("Quando você sorri para a barriga, seu bebê percebe aquela energia suave.", 1, 42),
    ("A ternura de preparar o enxoval é amor em cada dobra de roupinha.", 1, 42),
    ("Você já desenvolveu um amor tão delicado por alguém que nunca viu. Que lindo.", 1, 42),
    ("Coloque a mão na barriga agora. Sinta a magia desse toque.", 1, 42),
    ("A maternidade começa com a mais delicada das decisões: amar incondicionalmente.", 1, 42),
    ("Cada cuidado que você tem com sua alimentação é um ato de ternura pelo bebê.", 1, 42),
    ("Seu bebê vai crescer sabendo que foi amado antes de conhecer o mundo.", 1, 42),
    ("A gentileza que você tem consigo mesma reflete no bebê que você está criando.", 1, 42),
    ("Existe uma doçura no olhar de uma mãe esperando seu filho que é incomparável.", 1, 42),
    ("Durma abraçada ao seu travesseiro como vai abraçar o bebê em breve.", 20, 42),
    ("A ternura não é fraqueza — é a forma mais profunda de amor que existe.", 1, 42),
    ("Que seu filho sinta, através de cada célula, o quanto é esperado e amado.", 1, 42),
    ("Um carinho suave na barriga pode fazer o bebê se mover de alegria.", 18, 42),
    ("A delicadeza com que você cuida desta gestação é um presente ao seu filho.", 1, 42),
    ("Seus olhos vão brilhar diferente quando você olhar para esse bebê pela primeira vez.", 35, 42),
    ("Já existem sentimentos em você que só surgem quando tornamos mães.", 1, 42),
    ("A ternura de contar semanas, acompanhar o crescimento — isso é dedicação.", 1, 42),
    ("Seu bebê vai herdar a sua gentileza. Que presente para o mundo.", 1, 42),
    ("Cada consulta de pré-natal é um ato de ternura em forma de responsabilidade.", 1, 42),
    ("Que você possa se olhar com a mesma ternura com que olha para esse bebê.", 1, 42),
    ("A ternura que você sente pela vida que carrega vai crescer ainda mais.", 1, 42),
    ("Escreva uma carta para o bebê hoje. Esse ato de ternura será especial para sempre.", 1, 42),
    ("O coração de uma mãe é o lugar mais terno e mais seguro do universo.", 1, 42),
    ("Que seu bebê sinta sempre, ao longo da vida, a ternura que você sente agora.", 1, 42),
    ("A doçura com que você cuida de si é a doçura com que vai cuidar do bebê.", 1, 42),
    ("Amor, cuidado, ternura — você está repleta de tudo isso.", 1, 42),
    ("Em breve você vai cheirar a cabeça do seu bebê e nunca mais esquecer esse perfume.", 35, 42),
    ("A ternura que você guardou durante toda a gestação vai transbordar no nascimento.", 35, 42),
    ("Você é capaz de um amor tão suave e ao mesmo tempo tão invencível.", 1, 42),
]

# ── NOITE (night) — 35 mensagens ─────────────────────────────────────────────
NIGHT = [
    ("Boa noite, mamãe. Que o seu descanso seja tão profundo quanto o seu amor.", 1, 42),
    ("A noite chegou para lembrar que descansar é tão importante quanto agir.", 1, 42),
    ("Enquanto você dorme, seu bebê continua seu desenvolvimento. Que milagre noturno.", 1, 42),
    ("Que seu sono essa noite seja reparador e cheio de sonhos bonitos.", 1, 42),
    ("A noite é o momento em que você se permite simplesmente ser. Aproveite.", 1, 42),
    ("Deite-se sobre o lado esquerdo — favorece a circulação ao bebê.", 20, 42),
    ("Um travesseiro entre os joelhos pode fazer a diferença no seu conforto noturno.", 20, 42),
    ("O bebê às vezes é mais ativo à noite — é a dança noturna de vocês.", 20, 42),
    ("Antes de dormir, uma respiração profunda: inspire, segure, expire devagar.", 1, 42),
    ("Que esta noite seja de paz para você e de crescimento para o bebê.", 1, 42),
    ("O cansaço de hoje é a evidência do quanto você deu. Amanhã, vai repor.", 1, 42),
    ("Amanhã haverá um novo dia, um novo começo e um dia a menos para o encontro.", 1, 42),
    ("A noite traz clareza. As preocupações do dia parecem menores às 3h da manhã.", 1, 42),
    ("Se o bebê te acordar com seus movimentos, sorria — ele está bem e ativo.", 14, 42),
    ("Uma boa noite de sono é tão nutritiva quanto uma boa refeição.", 1, 42),
    ("Que você adormeça sentindo gratidão por mais um dia de gestação.", 1, 42),
    ("Noites insônicas são comuns — não lute contra elas. Apenas descanse.", 27, 42),
    ("Se não conseguir dormir, ouça uma música suave ou um podcast de meditação.", 1, 42),
    ("Seu corpo usa o sono para reparar, nutrir e fazer o bebê crescer.", 1, 42),
    ("A noite sussurra: amanhã você vai acordar mais perto do grande encontro.", 1, 42),
    ("Ao adormecer, coloque uma mão na barriga. Diga boa noite para o bebê.", 1, 42),
    ("O silêncio da noite é o momento ideal para ouvir o que seu coração diz.", 1, 42),
    ("Feche os olhos. O dia foi seu. Agora a noite pertence ao descanso.", 1, 42),
    ("Que os anjos da sua guarda vejem sobre você e sobre o pequeno coração que você carrega.", 1, 42),
    ("A lua está no céu, o bebê está em você. Que noite especial.", 1, 42),
    ("Amanhã será incrível. Por enquanto, descanse e confie.", 1, 42),
    ("No terceiro trimestre, acomodar-se para dormir vira arte. Seja criativa.", 27, 42),
    ("Que cada despertar noturno te lembre de como é especial esse tempo com o bebê.", 14, 42),
    ("O sonho que você terá essa noite pode ser mais bonito do que imagina.", 1, 42),
    ("Boa noite, guerreira do dia. Descanse essa versão de você que tanto deu.", 1, 42),
    ("A noite protege. O sono restaura. Amanhã você estará mais forte.", 1, 42),
    ("Que seu corpo encontre a posição perfeita e seu coração encontre a paz.", 1, 42),
    ("Você merece um sono profundo e restaurador. Permita-se ter isso hoje.", 1, 42),
    ("A noite está passando. O bebê está crescendo. Tudo está caminhando.", 1, 42),
    ("Durma bem, mamãe. Amanhã mais um dia de amor te espera.", 1, 42),
]

# ── FLORAL (floral) — 35 mensagens ───────────────────────────────────────────
FLORAL = [
    ("Você está florescendo, assim como as flores que desabrocham em seu tempo certo.", 1, 42),
    ("Cada pétala de uma flor representa uma semana de amor que você dedicou ao bebê.", 1, 42),
    ("As flores nascem do mesmo solo que a vida — e você é esse solo fértil.", 1, 42),
    ("Como um jardim que precisa de água e luz, você precisa de cuidado e atenção.", 1, 42),
    ("A mais delicada das flores é resistente ao mesmo tempo. Assim como você.", 1, 42),
    ("Cada gravidez é uma flor única — a sua tem uma beleza que não se repete.", 1, 42),
    ("O perfume das flores lembra que existem coisas belas em cada momento da vida.", 1, 42),
    ("Como o jardim floresce com cuidado diário, seu bebê cresce com seu amor constante.", 1, 42),
    ("Uma flor não compete com outra para florir. Você também não precisa comparar sua gestação.", 1, 42),
    ("Como as pétalas protegem o centro da flor, você protege o centro da sua vida.", 1, 42),
    ("Que sua vida floresça nessa gestação como nunca antes floresceu.", 1, 42),
    ("O jardim mais bonito é aquele que recebe amor e paciência — como o seu bebê.", 1, 42),
    ("Flores precisam de estações difíceis para florescer. Seus desafios te preparam.", 1, 42),
    ("Como a rosa tem espinhos mas é amada por sua beleza, a gestação tem dores mas é preciosa.", 1, 42),
    ("Plante intenções boas hoje: que elas floresçam junto com o seu bebê.", 1, 42),
    ("O girassol segue a luz do sol. Siga o que te faz bem durante essa gestação.", 1, 42),
    ("Como as flores abrem ao amanhecer, cada novo dia desta gestação abre novas possibilidades.", 1, 42),
    ("Você é o jardim e também a jardineira. Cuide-se como cuidaria de algo precioso.", 1, 42),
    ("Cada flor foi semente antes de florescer. Seu bebê já está no caminho do florescimento.", 1, 42),
    ("A lavanda acalma. A camomila restaura. A natureza tem remédios para cada momento.", 1, 42),
    ("Como flores diferentes têm fragrâncias diferentes, cada mãe tem seu modo único de amar.", 1, 42),
    ("Que o florescimento que você vive agora seja visível em cada aspecto da sua vida.", 1, 42),
    ("Uma flor não se apressa para florescer antes da hora. Confie no seu tempo.", 1, 42),
    ("Como o jardim precisa de podas, às vezes precisamos deixar ir o que não serve.", 1, 42),
    ("Flores silvestres crescem sem cuidado excessivo — e são as mais belas.", 1, 42),
    ("Você está em plena floração. Nada está faltando para você ser mãe.", 1, 42),
    ("O jardim da maternidade que você planta agora vai ser colhido a vida toda.", 1, 42),
    ("Como as flores voltam após o inverno, você vai florescer depois dos desafios.", 1, 42),
    ("Que sua chegada ao parto seja como uma flor chegando ao auge de sua beleza.", 35, 42),
    ("O bebê que você carrega é a semente mais preciosa que já existiu.", 1, 42),
    ("Flores e mães têm isso em comum: sua beleza vem de dentro para fora.", 1, 42),
    ("Como o jardim tem diferentes flores em diferentes épocas, cada fase da gestação tem seu charme.", 1, 42),
    ("Que você veja beleza em si mesma com a mesma facilidade que vê beleza nas flores.", 1, 42),
    ("Uma flor não precisa tentar ser linda. Ela simplesmente é. Assim como você.", 1, 42),
    ("O florescimento mais bonito do mundo é o de uma mãe amorosa.", 1, 42),
]

# ── SOL / AURORA (sunrise) — 35 mensagens ────────────────────────────────────
SUNRISE = [
    ("Como o sol nasce todos os dias, seu amor por esse bebê se renova a cada amanhecer.", 1, 42),
    ("Bom dia, mamãe! O sol trouxe mais um dia de graça para você e seu bebê.", 1, 42),
    ("A luz da manhã é o símbolo perfeito do novo começo que você vive nessa gestação.", 1, 42),
    ("Como o sol aquece a terra, seu amor aquece o pequenininho que cresce em você.", 1, 42),
    ("Cada amanhecer é uma nova chance de se conectar com o bebê e consigo mesma.", 1, 42),
    ("O sol nasce sem esforço — confie que o que é natural acontece no tempo certo.", 1, 42),
    ("Que a claridade do dia ilumine também seu coração de mãe.", 1, 42),
    ("Como o sol clareia o que estava escuro, seu amor ilumina o futuro do seu filho.", 1, 42),
    ("Aproveite a luz da manhã — ela tem poder real sobre o seu humor e energia.", 1, 42),
    ("Um café da manhã nutritivo com a luz do sol é um presente para vocês dois.", 1, 42),
    ("O sol não pede permissão para brilhar. Você também não precisa pedir para ser feliz.", 1, 42),
    ("Como o girassol se volta para o sol, volte-se para tudo que te faz bem hoje.", 1, 42),
    ("A vitamina D do sol matinal é importante para você e para o desenvolvimento do bebê.", 1, 42),
    ("Que o nascer do sol te lembre que cada dia é um presente para ser vivido.", 1, 42),
    ("O sol é a estrela mais próxima — e você é a estrela mais próxima do seu bebê.", 1, 42),
    ("Como o sol atravessa as nuvens, você atravessa os momentos difíceis com brilho.", 1, 42),
    ("Saia para o sol por 15 minutinhos hoje. A energia que ele dá é incomparável.", 1, 42),
    ("O nascer do sol é a promessa de que o novo sempre vem. Assim como o seu bebê.", 1, 42),
    ("Que os raios do sol toquem sua pele e te lembrem de que você é energia e luz.", 1, 42),
    ("Como o sol ilumina o caminho dos viajantes, sua presença ilumina o caminho do bebê.", 1, 42),
    ("Um pouco de sol na janela pela manhã é tudo que o dia precisa para começar bem.", 1, 42),
    ("O sol nasceu hoje, mais um dia foi dado a você e ao seu bebê. Que dádiva.", 1, 42),
    ("Como o pôr do sol traz beleza antes da noite, os momentos difíceis trazem crescimento.", 1, 42),
    ("Que a luz do dia ilumine cada preocupação e mostre que há saída para tudo.", 1, 42),
    ("O sol recarga nossas energias. Você está com a carga completa de amor.", 1, 42),
    ("Como o sol é constante no céu, seu amor por esse bebê é constante no coração.", 1, 42),
    ("Manhãs ensolaradas ou chuvosas, você está aqui para o bebê. Isso é o que importa.", 1, 42),
    ("A luz do sol não escolhe a quem iluminar. O amor de mãe também não.", 1, 42),
    ("Que cada manhã daqui ao parto seja uma descoberta nova e bonita.", 1, 42),
    ("O sol da manhã é o primeiro presente do dia. Você é o maior presente da vida do bebê.", 1, 42),
    ("Como os pássaros cantam ao amanhecer, que seu coração cante de gratidão hoje.", 1, 42),
    ("O sol nasceu. O bebê está crescendo. A vida está acontecendo. Que belo dia.", 1, 42),
    ("Que os próximos dias sejam ensolarados — dentro e fora de você.", 1, 42),
    ("O nascer do sol de hoje é o mesmo que o seu bebê vai ver daqui a pouco.", 35, 42),
    ("Cada amanhecer te aproxima um dia mais do encontro mais especial da sua vida.", 1, 42),
]

# ── TRANSFORMAÇÃO (transformation) — 35 mensagens ────────────────────────────
TRANSFORMATION = [
    ("Você não é mais a mesma pessoa que começou essa gestação — e isso é lindo.", 1, 42),
    ("A transformação que você vive é a mais profunda que um ser humano pode experimentar.", 1, 42),
    ("Como a lagarta não sabe que se tornará borboleta, você ainda não sabe o quanto vai crescer.", 1, 42),
    ("A gestação transforma não só o corpo, mas a alma, o coração e a visão de mundo.", 1, 42),
    ("Cada semana de gestação é uma metamorfose — você emerge diferente e mais completa.", 1, 42),
    ("A transformação é desconfortável porque envolve mudança real. Você está mudando de verdade.", 1, 42),
    ("Como a borboleta, você está emergindo de um casulo de amor e transformação.", 1, 42),
    ("Você está desenvolvendo capacidades que não sabia que tinha. A maternidade te expande.", 1, 42),
    ("A mulher que você está se tornando é mais forte, mais sábia e mais amorosa.", 1, 42),
    ("Transformar-se não é perder quem você era — é integrar quem você sempre pode ser.", 1, 42),
    ("Seu bebê está passando por uma transformação incrível dentro de você semana a semana.", 1, 42),
    ("Na 4ª semana, eram células. Hoje é um ser com batimentos, expressões e personalidade.", 4, 42),
    ("Da semente ao bebê, que jornada de transformação acontece dentro de você.", 1, 42),
    ("Você está testemunhando a maior transformação da sua vida. Registre-a.", 1, 42),
    ("Mudanças externas no corpo são visíveis, mas as internas são ainda mais profundas.", 1, 42),
    ("A transformação que a maternidade provoca dura para sempre. Você já começou.", 1, 42),
    ("Cada célula do seu bebê foi criada a partir das suas células. Que transformação compartilhada.", 1, 42),
    ("Como a água se transforma em vapor e depois em chuva, você está em constante renovação.", 1, 42),
    ("As prioridades que estão mudando em você são sinais de crescimento, não de perda.", 1, 42),
    ("A mulher que vai sair do parto não é a mesma que entrou. É uma versão mais poderosa.", 35, 42),
    ("Você está aprendendo que pode amar de formas que não conhecia antes.", 1, 42),
    ("Transformar-se custa. Mas o que se conquista no outro lado é incomparável.", 1, 42),
    ("Seu bebê está se transformando de embrião a pessoa. Você de mulher a mãe. Juntos.", 1, 42),
    ("A transformação hormonal que você vive tem propósito: preparar tudo para o bebê.", 1, 42),
    ("Como o crisálida parece rígida por fora mas guarda vida por dentro, assim é a gestação.", 1, 42),
    ("A curiosidade do bebê em desenvolvimento é uma das maiores maravilhas da natureza.", 1, 42),
    ("Você está se tornando a pessoa que seu filho vai chamar de mãe. Que honra.", 1, 42),
    ("A cada semana, novas capacidades surgem no bebê e novas profundezas surgem em você.", 1, 42),
    ("Transformações assustam porque são desconhecidas. Mas a maternidade é destino.", 1, 42),
    ("Aceite as mudanças no seu corpo com gratidão — são evidências de transformação sagrada.", 1, 42),
    ("Você está em metamorfose. O resultado dessa transformação é uma mãe incrível.", 1, 42),
    ("Como o sol transforma a semente em planta, seu amor transforma células em pessoa.", 1, 42),
    ("Que você olhe para essa transformação com admiração, não com resistência.", 1, 42),
    ("A maternidade é a mais completa transformação da identidade humana.", 1, 42),
    ("Você vai sair dessa gestação transformada e mais você mesma do que nunca.", 1, 42),
]

# ── SAÚDE (health) — 35 mensagens ────────────────────────────────────────────
HEALTH = [
    ("Beba pelo menos 2 litros de água por dia. A hidratação é essencial para você e seu bebê.", 1, 42),
    ("Uma caminhada leve de 20 a 30 minutos faz maravilhas para o corpo e a mente.", 1, 42),
    ("Evite ficar muito tempo em pé. Sente-se e eleve as pernas quando possível.", 14, 42),
    ("Deitar do lado esquerdo melhora a circulação sanguínea para o bebê.", 20, 42),
    ("Exercícios de Kegel fortalecem o assoalho pélvico. Faça 10 repetições, 3x ao dia.", 10, 42),
    ("Yoga para gestantes alivia dores nas costas, melhora a postura e reduz o estresse.", 12, 42),
    ("Use sapatos confortáveis. Seus pés podem inchar, especialmente à tarde.", 28, 42),
    ("Evite sauna, banheira quente e exposição prolongada ao sol forte.", 1, 42),
    ("Massagens nos pés e tornozelos com movimentos suaves aliviam o inchaço.", 25, 42),
    ("Pratique respiração profunda: inspire em 4 tempos, segure em 4, expire em 6.", 1, 42),
    ("Exercícios de alongamento suave antes de dormir melhoram o sono.", 1, 42),
    ("A natação é um dos exercícios mais recomendados na gestação — alivia o peso.", 14, 42),
    ("Câimbras nas pernas são comuns. Alongue o músculo, hidrate-se e consuma cálcio.", 20, 42),
    ("Azia é comum na gravidez. Coma devagar, em porções menores, e evite deitar logo após.", 14, 42),
    ("Mude de posição lentamente para evitar tonturas — levante-se devagar da cama.", 1, 42),
    ("O inchaço nos pés é normal, mas informe seu médico se for súbito ou assimétrico.", 25, 42),
    ("Evite ambientes com fumaça de cigarro — prejudica o desenvolvimento do bebê.", 1, 42),
    ("O descanso não é luxo — é necessidade médica durante a gestação.", 1, 42),
    ("Pratique meditação por 10 minutos ao dia para reduzir ansiedade.", 1, 42),
    ("O sono de qualidade é tão importante quanto a alimentação para o bebê.", 1, 42),
    ("Evite levantamento de peso acima de 5kg a partir do segundo trimestre.", 14, 42),
    ("Cuide dos seus dentes — a saúde bucal está ligada à saúde gestacional.", 1, 42),
    ("Use protetor solar — a pele fica mais sensível durante a gestação.", 1, 42),
    ("Mantenha suas consultas de pré-natal em dia — elas são sua maior proteção.", 1, 42),
    ("Evite o estresse sempre que possível — o cortisol afeta o bebê também.", 1, 42),
    ("Peça ajuda quando precisar. Cuidar de si é cuidar do bebê.", 1, 42),
    ("Evite ficar deitada de costas por longos períodos no segundo e terceiro trimestres.", 20, 42),
    ("Dorme melhor colocando um travesseiro entre os joelhos ao deitar de lado.", 20, 42),
    ("Roupa justa dificulta a circulação. Prefira roupas confortáveis e amplas.", 14, 42),
    ("Monitorar os movimentos fetais após 28 semanas é muito importante.", 28, 42),
    ("A postura correta ao sentar protege sua coluna durante a gestação.", 14, 42),
    ("Banhos mornos (não quentes) são ótimos para relaxar os músculos.", 1, 42),
    ("Caminhar descalça em casa fortalece os pés e melhora o equilíbrio.", 1, 42),
    ("A pilates adaptada para gestantes melhora a postura e alivia dores.", 12, 42),
    ("Fortalecer os músculos do core (adaptado para grávidas) facilita o parto.", 14, 42),
]

# ── NUTRIÇÃO (nutrition) — 35 mensagens ──────────────────────────────────────
NUTRITION = [
    ("Ácido fólico é fundamental no primeiro trimestre. Feijão, lentilha e folhas verde-escuras.", 1, 13),
    ("O ferro previne anemia: carnes magras, fígado, feijão, espinafre e sementes de abóbora.", 1, 42),
    ("Cálcio fortalece os ossos do bebê. Leite, iogurte, couve e brócolis são excelentes fontes.", 14, 42),
    ("Ômega-3 apoia o desenvolvimento cerebral. Sardinha, atum light e salmão são ótimas opções.", 14, 42),
    ("Evite queijos moles não pasteurizados, sushi e carnes cruas durante a gestação.", 1, 42),
    ("Gengibre em chá pode ajudar a aliviar a náusea matinal.", 1, 12),
    ("Refeições pequenas a cada 2-3 horas ajudam a estabilizar a glicemia e reduzir enjoos.", 1, 42),
    ("Vitamina D: um pouco de sol matinal ajuda muito! Além de ovos e peixes.", 1, 42),
    ("Evite alimentos ultraprocessados, ricos em sódio, açúcar e gordura trans.", 1, 42),
    ("Abacate é rico em gorduras saudáveis e folato — perfeito para a gestação.", 1, 42),
    ("No terceiro trimestre, refeições menores e mais frequentes ajudam com o refluxo.", 27, 42),
    ("Banana, laranja e abacaxi fornecem vitamina C que melhora a absorção do ferro.", 1, 42),
    ("Grão-de-bico e lentilha são fontes ricas de proteína vegetal e ferro.", 1, 42),
    ("Inclua castanhas e nozes na dieta — fontes de gorduras boas e magnésio.", 1, 42),
    ("Ovos são excelentes fontes de proteína e colina, essencial para o cérebro do bebê.", 1, 42),
    ("Batata-doce é rica em beta-caroteno e fibras — nutritiva e versátil.", 1, 42),
    ("Consuma pelo menos 5 porções de frutas e verduras variadas por dia.", 1, 42),
    ("O iogurte natural é rico em probióticos e cálcio — ótimo para você e o bebê.", 1, 42),
    ("Evite cafeína em excesso. O limite recomendado é 200mg/dia.", 1, 42),
    ("Beterraba é rica em ferro e ácido fólico — excelente para gestantes.", 1, 42),
    ("Aveia no café da manhã fornece energia prolongada e fibras para o intestino.", 1, 42),
    ("Quinoa é um superalimento: proteína completa, ferro e magnésio.", 1, 42),
    ("Bebidas açucaradas podem contribuir para diabetes gestacional. Prefira água.", 1, 42),
    ("Chia e linhaça são fontes de ômega-3 vegetal e fibras.", 1, 42),
    ("Alimentação colorida é nutrição completa — varie as cores no prato.", 1, 42),
    ("Consuma proteínas a cada refeição para manter energia e saciedade.", 1, 42),
    ("Prepare lanches saudáveis para não comer em excesso nas refeições principais.", 1, 42),
    ("Alimentos ricos em triptofano (banana, leite, aveia) melhoram o sono e o humor.", 1, 42),
    ("A vitamina B6 (banana, frango, batata) pode ajudar a reduzir náuseas.", 1, 12),
    ("O zinco é importante para a imunidade do bebê: encontrado em carnes e leguminosas.", 1, 42),
    ("Fibras previnem a prisão de ventre comum na gestação. Consuma cereais integrais.", 1, 42),
    ("Frutos vermelhos (morango, mirtilo) são ricos em antioxidantes e vitamina C.", 1, 42),
    ("Evite alimentos muito apimentados se você tiver azia frequente.", 14, 42),
    ("O magnésio (castanha, aveia, feijão) ajuda a reduzir câimbras noturnas.", 20, 42),
    ("Mel e frutas secas são fontes de energia rápida para o lanche da tarde.", 1, 42),
]

# ── CURIOSIDADES (curiosity) — 35 mensagens ───────────────────────────────────
CURIOSITY = [
    ("Seu bebê já tem impressões digitais únicas desde a 10ª semana de gestação.", 10, 42),
    ("O coração do bebê bate cerca de 140-160 vezes por minuto — o dobro do adulto.", 6, 42),
    ("Bebês sonham no útero! Movimentos rápidos dos olhos (REM) foram observados.", 23, 42),
    ("Seu bebê consegue distinguir a voz da mamãe de todas as outras vozes.", 18, 42),
    ("O bebê já soluça dentro do útero — você pode sentir como movimentos rítmicos.", 14, 42),
    ("A partir da 28ª semana, o bebê pode sentir luz através da parede do abdômen.", 28, 42),
    ("Os bebês nascem com mais ossos que adultos — cerca de 270 contra 206.", 1, 42),
    ("O bebê pratica expressões faciais como sorrir e franzir o cenho.", 14, 42),
    ("O vernix caseosa cobre o bebê como um creme protetor natural de sua pele.", 20, 40),
    ("Bebês que ouvem músicas no útero podem reconhecê-las após o nascimento.", 18, 42),
    ("A placenta produz hormônios suficientes para substituir as glândulas do corpo.", 1, 42),
    ("Seu volume sanguíneo aumenta até 50% durante a gravidez.", 8, 42),
    ("O bebê começa a engolir líquido amniótico por volta da 11ª semana.", 11, 42),
    ("O cordão umbilical tem três vasos: duas artérias e uma veia.", 1, 42),
    ("As sobrancelhas e cílios do bebê aparecem por volta da 22ª semana.", 22, 42),
    ("O lanugo (penugem fina) começa a cobrir o bebê por volta da 16ª semana.", 16, 36),
    ("Bebês já choram no útero — cientistas detectaram movimentos faciais de choro.", 28, 42),
    ("O cérebro do bebê forma 250.000 neurônios por minuto nas primeiras semanas.", 1, 13),
    ("O sentido do olfato do bebê já está desenvolvido dentro do útero.", 20, 42),
    ("A língua do bebê já tem papilas gustativas por volta da 13ª semana.", 13, 42),
    ("O bebê se move mais quando a mãe está deitada.", 14, 42),
    ("A pele do bebê é quase transparente no início — você veria veias e órgãos.", 8, 16),
    ("Bebês no útero têm ciclos de sono de 20-40 minutos.", 20, 42),
    ("O bebê começa a respirar praticando movimentos respiratórios por volta da 9ª semana.", 9, 42),
    ("O feto tem reflexo de sucção desde a 15ª semana.", 15, 42),
    ("O coração do bebê começa a bater por volta de 22 dias após a concepção.", 1, 6),
    ("O bebê é capaz de piscar os olhos dentro do útero a partir da 26ª semana.", 26, 42),
    ("Sua placenta compartilha material genético entre mãe e filho.", 1, 42),
    ("O útero pode expandir até 500 vezes seu tamanho original durante a gestação.", 1, 42),
    ("O bebê produz urina dentro do útero a partir da 8ª semana.", 8, 42),
    ("A posição fetal é o bebê se adaptando ao espaço disponível.", 1, 42),
    ("Bebês reconhecem o rosto da mãe em fotos com apenas horas de vida.", 35, 42),
    ("O bebê pode sentir as emoções da mãe através dos hormônios que circulam.", 1, 42),
    ("A memória do bebê começa a se formar ainda no útero.", 20, 42),
    ("O bebê consegue distinguir sabores no líquido amniótico desde a 28ª semana.", 28, 42),
]

# ── ALERTAS MÉDICOS (medical) — 35 mensagens ─────────────────────────────────
MEDICAL = [
    ("Consulte seu médico imediatamente se sentir dor abdominal intensa ou sangramento.", 1, 42),
    ("Movimentos fetais devem ser monitorados após 28 semanas. Menos de 10 em 2h: ligue.", 28, 42),
    ("O pré-natal regular é fundamental. Nunca pule uma consulta programada.", 1, 42),
    ("Sinais de pré-eclâmpsia: pressão alta, inchaço súbito, dores de cabeça. Consulte.", 20, 42),
    ("Vacinas dTpa (coqueluche) são recomendadas entre a 27ª e 36ª semana.", 27, 36),
    ("Diabetes gestacional: faça o teste de glicose entre 24 e 28 semanas.", 20, 30),
    ("Refluxo é comum. Coma devagar, evite deitar após comer, consulte se persistir.", 14, 42),
    ("Câimbras são frequentes. Alivie com alongamento, hidratação e cálcio.", 20, 42),
    ("Contrações regulares antes da 37ª semana: procure o hospital imediatamente.", 20, 37),
    ("Sinais de trabalho de parto: contrações regulares, perda do tampão mucoso.", 38, 42),
    ("Exames de sangue e urina regulares monitoram sua saúde e a do bebê.", 1, 42),
    ("Alteração súbita na visão pode indicar pressão alta. Informe seu médico.", 20, 42),
    ("Corrimento com odor forte ou coceira intensa: consulte seu ginecologista.", 1, 42),
    ("A anemia gestacional é comum e tratável. Faça o exame de hemograma.", 1, 42),
    ("A listeria é perigosa: evite frios embutidos, salmão defumado e patês.", 1, 42),
    ("Febre acima de 38°C na gestação deve ser avaliada pelo médico.", 1, 42),
    ("O ultrassom morfológico entre 20-24 semanas avalia o desenvolvimento fetal.", 20, 24),
    ("O exame de glicemia (TOTG) detecta diabetes gestacional.", 24, 28),
    ("Dor lombar intensa pode ser sinal de infecção urinária. Faça urocultura.", 1, 42),
    ("Se o bebê parar de se mover por mais de 2 horas: vá ao pronto-socorro.", 28, 42),
    ("O grupo sanguíneo e fator Rh são essenciais para planejar a gestação.", 1, 14),
    ("Infecção urinária na gestação aumenta risco de parto prematuro. Trate sempre.", 1, 42),
    ("Vacina da gripe é segura e recomendada em qualquer trimestre da gestação.", 1, 42),
    ("Medicamentos sem prescrição podem ser perigosos na gestação. Sempre consulte.", 1, 42),
    ("A bolsa rompida exige ir imediatamente ao hospital, mesmo sem contrações.", 35, 42),
    ("Faça o ecocardiograma fetal entre 28 e 32 semanas.", 28, 32),
    ("Inchaço súbito nas mãos e rosto pode ser sinal de pré-eclâmpsia.", 20, 42),
    ("A depressão e ansiedade gestacional são condições médicas — procure apoio.", 1, 42),
    ("Toxoplasmose: evite contato com fezes de gato e carnes cruas mal passadas.", 1, 42),
    ("O streptococcus B é testado entre 35 e 37 semanas.", 35, 37),
    ("Hemorroidas são comuns na gestação. Fale com seu médico sobre tratamento.", 20, 42),
    ("Pressão baixa pode causar tontura ao levantar. Levante-se devagar.", 1, 42),
    ("Coceira generalizada no terceiro trimestre pode indicar colestase. Consulte.", 27, 42),
    ("Varizes nas pernas são comuns. Use meias de compressão se indicado.", 20, 42),
    ("A consulta com anestesiologista antes do parto ajuda a planejar a analgesia.", 32, 38),
]


# ── Seed function ─────────────────────────────────────────────────────────────

MSG_MAP = {
    "daily":          DAILY,
    "health":         HEALTH,
    "nutrition":      NUTRITION,
    "curiosity":      CURIOSITY,
    "medical":        MEDICAL,
    "strength":       STRENGTH,
    "nature":         NATURE,
    "serenity":       SERENITY,
    "ocean":          OCEAN,
    "body":           BODY,
    "tenderness":     TENDERNESS,
    "night":          NIGHT,
    "floral":         FLORAL,
    "sunrise":        SUNRISE,
    "transformation": TRANSFORMATION,
}

EMOJIS = {
    "daily": "🌸", "health": "💚", "nutrition": "🥗",
    "curiosity": "✨", "medical": "🏥", "strength": "💪",
    "nature": "🌿", "serenity": "☮️", "ocean": "🌊",
    "body": "🫶", "tenderness": "💕", "night": "🌙",
    "floral": "🌺", "sunrise": "☀️", "transformation": "🦋",
}


def seed():
    app = create_app()
    with app.app_context():
        db.create_all()
        if db.session.query(Category).first():
            print("Banco já populado. Use --reset para recriar.")
            return

        print("Populando banco de dados...")
        cat_map = {}
        for cat_data in CATEGORIES:
            cat = Category(**cat_data)
            db.session.add(cat)
            db.session.flush()
            cat_map[cat_data["slug"]] = cat.id
            print(f"  Categoria: {cat_data['name']}")

        total = 0
        for slug, msgs in MSG_MAP.items():
            emoji = EMOJIS[slug]
            for idx, (content, wmin, wmax) in enumerate(msgs):
                db.session.add(Message(
                    content=content, emoji=emoji,
                    category_id=cat_map[slug],
                    week_min=wmin, week_max=wmax,
                    day_index=idx, active=True,
                ))
                total += 1

        db.session.commit()
        print(f"\n  {total} mensagens em {len(CATEGORIES)} categorias")
        for slug, msgs in MSG_MAP.items():
            print(f"  - {slug}: {len(msgs)}")
        print("\nBanco de dados pronto!")


if __name__ == "__main__":
    import sys
    if "--reset" in sys.argv:
        app = create_app()
        with app.app_context():
            db.drop_all()
    seed()
