"""add more attributes to message

Revision ID: b4cff5fa8864
Revises: de2a7bb06e10
Create Date: 2026-02-14 18:25:39.364708

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4cff5fa8864'
down_revision: Union[str, None] = 'de2a7bb06e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('motivacional', 'saude', 'emocional', 'autocuidado', 'mindfulness', 'desenvolvimento', 'bebe', 'conexao', 'mensagem_do_bebe', 'nutricao', 'pratica', 'parto', 'relacionamento', 'diversao', 'curiosidade', 'celebracao', 'inspiracao', name='messagecategory'), nullable=False),
    sa.Column('type', sa.Enum('padrao', 'floral', 'oceano', 'transformacao', 'noite', 'natureza', 'seu_corpo', 'sol', 'serenidade', 'forca', 'ternura', name='messagetype'), nullable=False),
    sa.Column('onlyPremium', sa.Boolean(), nullable=False),
    sa.Column('week_min', sa.Integer(), nullable=True),
    sa.Column('week_max', sa.Integer(), nullable=True),
    sa.Column('trimester', sa.Integer(), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('daily_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('emoji', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=14), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('daily_messages')
    # ### end Alembic commands ###
